name: Build
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: cachix/install-nix-action@v13
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210604_8e6ee1b/install
          extra_nix_config: |
            experimental-features = nix-command flakes

      - run: |
          nix build .#miniond -o ./result-static -L
          echo "artifact_static=$(readlink ./result-static)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: miniond-static
          path: "${{ env.artifact_static }}/bin/miniond"
